name: Validate Files 
on: push
jobs:
    file-validate:
        runs-on: "ubuntu-latest"

        steps:
        - name: Get repo code on VM
          uses: actions/checkout@v4
        
        - name: Validate html file
          run: test -f index.html
          
        - name: Validate JS file
          run: test -f script.js